version: '3.8'
services:
    brouter-web:
        build: .
        ports:
            - '8084:80'
        volumes:
            - './config.js:/usr/share/nginx/html/config.js'
            #            - "./keys.js:/usr/share/nginx/html/keys.js"
            - './profiles:/usr/share/nginx/html/profiles'
        restart: unless-stopped
